### PR TITLE
Allow installing with symfony 5

### PR DESCRIPTION
**Pull request by peterculak**

### CODE REVIEW

**Comment by allansun** [comment]
Please do not modify the package name

**Comment by allansun** [comment]
Also without properly tested with Symfony 5, I am afraid I cannot merge this pull request.

I will, however, try to put some unit tests and let it run against Symfony 5 to see if there's any conflicts.

**Comment by peterculak** [comment]
ok let's close this PR then and if you make it work with symfony 5 let me know :)

**Comment by allansun** [comment]
@peterculak 

I've just updated this package to make it compatible with Symfony 5.

When you update your kubernetes/php-client package you may notice it still uses older version of kubernetes/php-runtime. It is because kubernetes/php-client is automatically generated daily when new version of Kubernetes swagger file is available, it updates the composer requirements commits then.  Since new version of kubernetes/php-client was just rolled out, it will only be available in later version of kubernetes/php-client.

Should you wish to use the new kubernetes/php-runtime now, you can specify the version in your own composer file "kubernetes/php-runtime":"1.0.5".

**Comment by peterculak** [comment]
thanx it works now :)

**Pull request closed without merging**
